// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEYZ3YUs5CZJr7YIeYMJZxQNZAQRo0uk8',
    appId: '1:475648889870:web:e4d0b58b880fff0f18985f',
    messagingSenderId: '475648889870',
    projectId: 'weather-app-262e0',
    authDomain: 'weather-app-262e0.firebaseapp.com',
    storageBucket: 'weather-app-262e0.firebasestorage.app',
    measurementId: 'G-JMMHNVHYEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5z0oaRFzvaddAhMVrLiHYG-m1Z1PWkn8',
    appId: '1:475648889870:android:4b27c1f51c8871e118985f',
    messagingSenderId: '475648889870',
    projectId: 'weather-app-262e0',
    storageBucket: 'weather-app-262e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrZK9L4LLpDw8bDpNmhezkJoOV5DwvtRQ',
    appId: '1:475648889870:ios:6e2b5024813f137718985f',
    messagingSenderId: '475648889870',
    projectId: 'weather-app-262e0',
    storageBucket: 'weather-app-262e0.firebasestorage.app',
    iosClientId: '475648889870-vtbbag3joa8tvelpimtm3ha7aaphkbk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrZK9L4LLpDw8bDpNmhezkJoOV5DwvtRQ',
    appId: '1:475648889870:ios:6e2b5024813f137718985f',
    messagingSenderId: '475648889870',
    projectId: 'weather-app-262e0',
    storageBucket: 'weather-app-262e0.firebasestorage.app',
    iosClientId: '475648889870-vtbbag3joa8tvelpimtm3ha7aaphkbk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEYZ3YUs5CZJr7YIeYMJZxQNZAQRo0uk8',
    appId: '1:475648889870:web:3a68d15b4bd4307618985f',
    messagingSenderId: '475648889870',
    projectId: 'weather-app-262e0',
    authDomain: 'weather-app-262e0.firebaseapp.com',
    storageBucket: 'weather-app-262e0.firebasestorage.app',
    measurementId: 'G-J0JLPQ1LLN',
  );
}
